version: '3'
services:
  vue-app:
    image: node:latest
    container_name: vue-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npm start"